#!/usr/bin/env bash

# This script follows directory changes since last execution.
# It uses rsync program. See 3 main line below.
# For use it see script keepchanges.

# The directory tree will be next:
ROOT_DIR=/root/keepchanges
SRC_DIR=""	# Absolute path.
WORK_DIR=""	# Relative path.
# ${SRC_DIR} - original directory must be set through parameter '-s'.
# ${WORK_DIR} - storage directory must be set through parameter '-d'. Can't be 'orig'.
# ROOT_DIR/orig/${SRC_DIR} - backup copy of original directories. Absolute path.
# ROOT_DIR/${WORK_DIR}${SRC_DIR} -
# directory for keep changes in ${SRC_DIR} since the last script execution. Absolute path.
# ROOT_DIR/${WORK_DIR}/${SRC_DIR}/filename.changes - delta changes for file 'filename'.
# ROOT_DIR/Changelog - common changelog for all changes.
# TMP_DIR - temporary working directory.
# TMP_DIR - created and removed every script execution.

RSYNC_EXE=/usr/bin/rsync

while getopts d:s: opt; do
  case $opt in
  d) WORK_DIR="$OPTARG" ;;
  s) SRC_DIR=$OPTARG ;;
  \?) exit 1 ;;
  esac
done

if [ -z "$WORK_DIR" ]; then echo "Error. No keep dir."; exit 1; fi
if [ "$WORK_DIR" = "orig" ]; then echo "Error. Wrong keep dir name. Shouldn't be 'orig'."; exit 1; fi
if [ -z "$SRC_DIR" ]; then echo "Error. No source dir."; exit 1; fi

KEEP_DIR=$ROOT_DIR/"${WORK_DIR}${SRC_DIR}"
ARCH_DIR=$ROOT_DIR/orig"$SRC_DIR"
if [ -f "$SRC_DIR/keepchanges.exclude" ]
then
  EXCLUDE_FILE="--exclude-from=$SRC_DIR/keepchanges.exclude"
else
  EXCLUDE_FILE=""
fi

if [ ! -d $ARCH_DIR ] # Is it the first time launch?
then
  mkdir -p $ARCH_DIR
  printf %b "First time sync the '$SRC_DIR' in the 'orig' ... "
  $RSYNC_EXE $EXCLUDE_FILE -rclpgo $SRC_DIR/ $ARCH_DIR
  printf %b "DONE.\n"
  exit 0
fi

printf %b "Check changes in '$SRC_DIR' ... "
itemized_changes=$($RSYNC_EXE -rclpgoin $EXCLUDE_FILE --del $SRC_DIR/ $ARCH_DIR) # Dry run.
changes=$(echo $itemized_changes | wc -w)
if [ "$changes" != 0 ]; then
  printf %b "DONE.\n"
  echo "$itemized_changes"
  echo "Keep changes in '$WORK_DIR' or sync with 'orig'?"
  read -p "Keep/Sync/[Skip]: " answer
  if [ "$answer" == "Sync" ]; then
    $RSYNC_EXE -rclpgo $EXCLUDE_FILE --del $SRC_DIR/ $ARCH_DIR
    exit 0;
  elif [ "$answer" != "Keep" ]; then
    exit 0;
  fi
else
  printf %b "No changes.\n"
  exit 0
fi

TMP_DIR=$(mktemp -d --tmpdir confXXXX)
mkdir -p $TMP_DIR/old

function keep_file_changes {
  local fpath="$1"
  mkdir -p $(dirname "$KEEP_DIR/${fpath}")
  cd $TMP_DIR
  diff -uN --no-dereference "old/$fpath" "new/$fpath" > $TMP_DIR/changes
  touch "$KEEP_DIR/${fpath}.changes"	# First time the file is missing.
  cat "$KEEP_DIR/${fpath}.changes" >> $TMP_DIR/changes
  /usr/bin/mv -fT $TMP_DIR/changes "$KEEP_DIR/${fpath}.changes"
}

# Three main lines. Trailing '/' very important. See man rsync.
$RSYNC_EXE -rmclpgo "$EXCLUDE_FILE" --compare-dest="$ARCH_DIR" "$SRC_DIR/" $TMP_DIR/new_with_dir
$RSYNC_EXE -rmclpgo "$EXCLUDE_FILE" $TMP_DIR/new_with_dir/ $TMP_DIR/new  #For skip empty directory
$RSYNC_EXE -rclpgob "$EXCLUDE_FILE" --backup-dir=$TMP_DIR/old --del "$SRC_DIR/" "$ARCH_DIR"

cd $TMP_DIR
echo $(date --rfc-3339=ns) "      " "${WORK_DIR}$SRC_DIR" > $TMP_DIR/Changelog_new
echo "$itemized_changes" >> $TMP_DIR/Changelog_new
echo '************************************************' >> $TMP_DIR/Changelog_new
changelog_file=$ROOT_DIR/$(echo "${SRC_DIR##/}" | tr / _).log
touch "$changelog_file"
cat "$changelog_file" >> $TMP_DIR/Changelog_new
/usr/bin/mv -fT $TMP_DIR/Changelog_new "$changelog_file"

cd $TMP_DIR/new
find -type f -or -type l |
  while read fpath
  do
    keep_file_changes "$fpath"
    /usr/bin/mv -fT "$TMP_DIR/new/$fpath" "$KEEP_DIR/$fpath"
    /usr/bin/rm -f "$TMP_DIR/old/$fpath"
  done
#find

cd $TMP_DIR/old
find -type f -or -type l |
  while read fpath
  do
    keep_file_changes "$fpath"
    /usr/bin/rm -f "$KEEP_DIR/$fpath"
  done
#find

rm -rf $TMP_DIR
