#!/bin/sh

KEEP_DIR=work
if [ -n "$1" ]; then KEEP_DIR="$1"
else 
  read -p "Keep in standart path? [work]: " answer
  if [ -n "$answer" ]; then KEEP_DIR="$answer"; fi
fi
for s in "/etc" "/usr/local/bin"
do
  /usr/local/bin/keepdirchanges -s "$s" -d "$KEEP_DIR"
done
